version: "3.9"

services:

  localstack:
    image: localstack/localstack:latest
    container_name: localstack-simple-blog-app
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sns,ses
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
    volumes:
      - "//var/run/docker.sock:/var/run/docker.sock"

  postgres:
    image: postgres:15.5
    container_name: postgres-simple-blog-app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simple-blog
    ports:
      - "5432:5432"
    volumes:
      - postgres-simple-blog-db:/var/lib/postgresql/data

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: simple-blog-app
    env_file:
      - .env
    depends_on:
      - postgres
      - localstack
    ports:
      - "8080:8080"

volumes:
  postgres-simple-blog-db:
