spring:
  application:
    name: simple-blog-backend

  profiles:
    active: dev

server:
  servlet:
    context-path: /api

application:
  image:
    max-size-mb: 5
    allowed-content-types:
      - image/jpeg
      - image/png
      - image/webp

